// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjWavMC11EiEKVMWiH6w7dlHIXSHfBpw',
    appId: '1:811504701411:web:70386eb1a91767c1b71ad6',
    messagingSenderId: '811504701411',
    projectId: 'giziku-mbg',
    authDomain: 'giziku-mbg.firebaseapp.com',
    storageBucket: 'giziku-mbg.firebasestorage.app',
    measurementId: 'G-7XYNS40XLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASm_XGxBZe1Kz9Hkj4NYp-bdGp3SW1szA',
    appId: '1:811504701411:android:864a288bade8215fb71ad6',
    messagingSenderId: '811504701411',
    projectId: 'giziku-mbg',
    storageBucket: 'giziku-mbg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhN0KvxqCMlPl6LFgnYqqCAnucrqT5N5k',
    appId: '1:811504701411:ios:c878a1bcff5d3ba4b71ad6',
    messagingSenderId: '811504701411',
    projectId: 'giziku-mbg',
    storageBucket: 'giziku-mbg.firebasestorage.app',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhN0KvxqCMlPl6LFgnYqqCAnucrqT5N5k',
    appId: '1:811504701411:ios:c878a1bcff5d3ba4b71ad6',
    messagingSenderId: '811504701411',
    projectId: 'giziku-mbg',
    storageBucket: 'giziku-mbg.firebasestorage.app',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjWavMC11EiEKVMWiH6w7dlHIXSHfBpw',
    appId: '1:811504701411:web:129a08246f8b464cb71ad6',
    messagingSenderId: '811504701411',
    projectId: 'giziku-mbg',
    authDomain: 'giziku-mbg.firebaseapp.com',
    storageBucket: 'giziku-mbg.firebasestorage.app',
    measurementId: 'G-3SJHDYNH8X',
  );
}
